### PR TITLE
Fix signature header add custom http timeout useragent

### PR DESCRIPTION
**Pull request by jasonwmiller**

### CODE REVIEW

**Comment by josepbigorra** [comment]
Very nice work ! It's been a while I use Go, you can for it if you will too.

**Review by josepbigorra — APPROVED** [review]

**Comment by jasonwmiller** [comment]
I know it's widely shared from this repo, so No need to fork for now. I only intended to fix the SignatureHeader and added the only options to handle two things that would be useful. 

But Let me know if you would rather not maintain this going forward, and we can discuss handing it off to me.

Thanks!

**Comment by josepbigorra** [comment]
@jasonwmiller https://github.com/averageflow/gohooks/releases/tag/v2.2.0

**Comment by jasonwmiller** [comment]
Thanks @josepbigorra

**Pull request merged**
